/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_deal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import javax.swing.ComboBoxEditor;
import javax.swing.JComboBox;

/**
 *
 * @author wathe
 */
public class AgenceInterface extends javax.swing.JFrame {

    /**
     * Creates new form AgenceInterface
     */
    public AgenceInterface() {
        initComponents();
    }
    Agence agence = new Agence();
    String localisation ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inscritClient = new javax.swing.JButton();
        inscritFournisseur = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ajoutRestaurant = new javax.swing.JButton();
        ajoutSpa = new javax.swing.JButton();
        ajoutHotel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        listFournisseur = new javax.swing.JButton();
        listRestaurant = new javax.swing.JButton();
        listClient = new javax.swing.JButton();
        listSpa = new javax.swing.JButton();
        listHotel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                                  Agence ");

        jLabel2.setText("Inscription :");

        inscritClient.setText("Client");
        inscritClient.setActionCommand("Client");
        inscritClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscritClientActionPerformed(evt);
            }
        });

        inscritFournisseur.setText("Fournisseur");
        inscritFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscritFournisseurActionPerformed(evt);
            }
        });

        jLabel3.setText("Ajout : ");

        ajoutRestaurant.setText("Restaurant");
        ajoutRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutRestaurantActionPerformed(evt);
            }
        });

        ajoutSpa.setText("Spa");
        ajoutSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutSpaActionPerformed(evt);
            }
        });

        ajoutHotel.setText("Hotel");
        ajoutHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutHotelActionPerformed(evt);
            }
        });

        jLabel4.setText("Affichage : ");

        listFournisseur.setText("listFournisseur");
        listFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFournisseurActionPerformed(evt);
            }
        });

        listRestaurant.setText("Restaurant");
        listRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listRestaurantActionPerformed(evt);
            }
        });

        listClient.setText("Client");
        listClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClientActionPerformed(evt);
            }
        });

        listSpa.setText("Spa");
        listSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSpaActionPerformed(evt);
            }
        });

        listHotel.setText("Hotel");
        listHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listHotelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(inscritClient, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(inscritFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(listClient, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(listFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ajoutHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(ajoutRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(listHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(listRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(221, 221, 221)
                    .addComponent(ajoutSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(415, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inscritClient, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(inscritFournisseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ajoutHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajoutRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listClient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(225, 225, 225)
                    .addComponent(ajoutSpa, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addGap(274, 274, 274)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscritClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscritClientActionPerformed
        TestCin testc = new TestCin();
        testc.setVisible(true);
        ClientInterface inscclient = new ClientInterface();
        testc.verifier.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                String ciin = testc.cin.getText();
                int cin = Integer.parseInt(ciin);
                Boolean tcin = agence.test_cin(cin);
                if ( tcin == true ){
                    inscclient.setVisible(true);
                    inscclient.cin.setText(ciin);
                    inscclient.valider.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent ae) {
                          String name_1 = inscclient.name.getText();
                          String prenom_1 = inscclient.prenom.getText();
                          String numtelf_1 = inscclient.num_tlf.getText();
                          int num = Integer.parseInt(numtelf_1);
                          agence.ajout_client(name_1, prenom_1, num, num);
                        }
                    });
                }else {
                    System.out.println("votre client existe déjà ! ");
                    
                }
            }
        });
        
        
                
    }//GEN-LAST:event_inscritClientActionPerformed

    private void ajoutSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutSpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutSpaActionPerformed

    private void listFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFournisseurActionPerformed
        agence.affiche_localisation();
    }//GEN-LAST:event_listFournisseurActionPerformed

    private void listClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClientActionPerformed
          agence.affiche_client();
        
    }//GEN-LAST:event_listClientActionPerformed

    private void listRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listRestaurantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listRestaurantActionPerformed

    private void listHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listHotelActionPerformed
        agence.affichage_hotel();
    }//GEN-LAST:event_listHotelActionPerformed

    private void listSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listSpaActionPerformed

    private void ajoutRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutRestaurantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutRestaurantActionPerformed

    private void ajoutHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutHotelActionPerformed
         AjoutHotel ajouthotel = new AjoutHotel();
        
         JComboBox<String> combo = new JComboBox<>();
         for (int i =0 ; i<agence.list_f.size(); i++){
             ajouthotel.combo.addItem(agence.list_f.get(i).getNom());
         }
          
         ajouthotel.setVisible(true);
         ajouthotel.ajouter.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent ae) {
                
                String desc = ajouthotel.description.getText();
                String prix_ii = ajouthotel.prix_i.getText();
                double prix_i = Double.parseDouble(prix_ii);
                String prix_dd = ajouthotel.prix_deal.getText();
                double prix_deal = Double.parseDouble(prix_ii);
                 java.util.Date date_debut =  ajouthotel.date_d.getDate();
                 java.util.Date date_fin = ajouthotel.date_fin.getDate();
                localisation = String.valueOf(ajouthotel.combo.getSelectedItem());
               java.util.Date date_ajout =  ajouthotel.date_ajout.getDate();
                agence.ajout_hotel(desc, prix_i, prix_deal, date_debut, date_fin, localisation, date_ajout);
             }
             
         });    
    }//GEN-LAST:event_ajoutHotelActionPerformed

    private void inscritFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscritFournisseurActionPerformed
         TestFournisseur testf = new TestFournisseur();
         
         testf.setVisible(true);
         testf.verifier.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent ae) {
                 String nom_1 = testf.nom_f.getText();
                 Boolean testn = agence.test_localisation(nom_1);
                 if (testn == true){
                     LocalisationIntreface loca = new LocalisationIntreface();
                     loca.setVisible(true);
                     loca.nom.setText(nom_1);
                     loca.valider.addActionListener(new ActionListener() {
                         @Override
                         public void actionPerformed(ActionEvent ae) {
                         String adr = loca.adress.getText();
                         String num_tlf = loca.num_telf.getText();
                         String mail = loca.email.getText();
                         String h_travail = loca.horaire.getText();
                         int num =Integer.parseInt(num_tlf);
                         agence.ajout_localisation(nom_1, adr, num, mail, h_travail);
                         }
                     });
                     
                     
                 }else{
                      System.out.println("votre client existe déjà ! ");
                 }
             }
         });
    }//GEN-LAST:event_inscritFournisseurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgenceInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgenceInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgenceInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgenceInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgenceInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutHotel;
    private javax.swing.JButton ajoutRestaurant;
    private javax.swing.JButton ajoutSpa;
    private javax.swing.JButton inscritClient;
    private javax.swing.JButton inscritFournisseur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton listClient;
    private javax.swing.JButton listFournisseur;
    private javax.swing.JButton listHotel;
    private javax.swing.JButton listRestaurant;
    private javax.swing.JButton listSpa;
    // End of variables declaration//GEN-END:variables
}
